#plugins:
#  - jekyll-remote-theme
#remote_theme: zivhub/monophase@main
remote_theme: pages-themes/primer
#remote_theme: eecs485staff/primer-spec
#remote_theme: riggraz/no-style-please
title: Curso de Astronom√≠a 2021
#description: A short description of your site's purpose
#name: Ernesto Nicola
#github:
#  private: true
